nuc_tr: 
  /net/sgi/metagenomics/data/from_moni/old.tzuhao/TreePaper/Paeru.v4/results.5/raxml/RAxML_bestTree.nuc
nuc_aln: 
# use the old data
  /net/sgi/metagenomics/data/from_moni/old.tzuhao/TreePaper/Paeru.v4/results.4/alignment/nuc.var.aln
raxml_model: 
  GTRGAMMAI
col_nuc_tr: 
  /net/sgi/metagenomics/data/from_moni/old.tzuhao/TreePaper/Paeru.v4/results.5/LogLikelihood.2/nuc_col_by_ll.nwk
# how many branches to keep
cutoff_perc: 0.75
#col_nuc_tr: 
#  /net/sgi/metagenomics/data/from_moni/old.tzuhao/TreePaper/Paeru.v4/results.4/per-site_LogLikelihood_cutoff25/nuc_col_by_psll.nwk
#cutoff_perc: 0.25
