nuc_tr: 
  /net/sgi/metagenomics/data/from_moni/old.tzuhao/TreePaper/Paeru.v4/results.4/raxml/RAxML_bipartitions.nuc.bs
nuc_aln: 
  /net/sgi/metagenomics/data/from_moni/old.tzuhao/TreePaper/Paeru.v4/results.4/alignment/nuc.var.aln
# the computation accepts only GAMMA model
raxml_model: 
  GTRGAMMA
col_nuc_tr: 
  /net/sgi/metagenomics/data/from_moni/old.tzuhao/TreePaper/Paeru.v4/results.4/per-site_LogLikelihood_cutoff25/nuc_col_by_psll.nwk
cutoff_perc: 0.25
