nuc_aln:
  /net/metagenomics/data/from_moni/old.tzuhao/TreePaper/Paeru.v4/results/alignment/nuc.var.aln
gpa_aln:
  /net/metagenomics/data/from_moni/old.tzuhao/TreePaper/Paeru.v4/results/gpa/gpa.var.aln
conc_aln: 
  /net/metagenomics/data/from_moni/old.tzuhao/TreePaper/Paeru.v4/results/cd/cutoff.v4/raxml_input/conc.aln
raxml_prtn: 
  /net/metagenomics/data/from_moni/old.tzuhao/TreePaper/Paeru.v4/results/cd/cutoff.v4/raxml_input/conc.prtn
col_constraint_tr: 
  /net/metagenomics/data/from_moni/old.tzuhao/TreePaper/Paeru.v4/results/cd/cutoff.v4/nuc.col.nwk
best_ml_tree: 
  /net/metagenomics/data/from_moni/old.tzuhao/TreePaper/Paeru.v4/results/cd/cutoff.v4/RAxML_bestTree.conc
bs_trees: 
  /net/metagenomics/data/from_moni/old.tzuhao/TreePaper/Paeru.v4/results/cd/cutoff.v4/bootstrap/RAxML_bootstrap.all
bs_best_ml_tree: 
  /net/metagenomics/data/from_moni/old.tzuhao/TreePaper/Paeru.v4/results/cd/cutoff.v4/RAxML_bipartitions.conc.bs
model:
  'BINGAMMA '
max_cores: 28
