nuc_pslls: 
  /net/metagenomics/data/from_moni/old.tzuhao/TreePaper/WhichTree_Sim.v7/results.v5.7/per-site_LogLikelihood/psll/raxml/RAxML_perSiteLLs.nuc_PSLL
rear_nuc_trs:
  /net/metagenomics/data/from_moni/old.tzuhao/TreePaper/WhichTree_Sim.v7/results.v5.7/per-site_LogLikelihood/psll/rear_trs.nwk
nuc_aln:
  /net/metagenomics/data/from_moni/old.tzuhao/TreePaper/WhichTree_Sim.v7/results.v5.6/alignment/nuc.var.aln
gpa_aln:
  /net/sgi/metagenomics/data/from_moni/old.tzuhao/TreePaper/WhichTree_Sim.v7/bin.v5/pseudo_gpa/gpa.var.fa
model:
  'BINGAMMA'
output_dir:
  /net/metagenomics/data/from_moni/old.tzuhao/TreePaper/WhichTree_Sim.v7/results.v5.7/ll_cutoff.old_gpa
psll_percs: [0.70, 0.80, 0.20, 0.30, 0.05, 0.15, 0.25, 0.35, 0.45, 0.55, 0.65, 0.75, 0.85, 0.95, 0.00]
norm_weight: True
weighted: False
