nuc_aln:
  /net/personal-backup/thkuo/Saure/results.3/CH3657/alignment/nuc.var.aln
gpa_aln:
  /net/personal-backup/thkuo/Saure/results.3/CH3657/gpa/gpa.var.aln
conc_aln: 
  /net/personal-backup/thkuo/Saure/results.3/CH3657/cd/raxml_input/conc.aln
raxml_prtn: 
  /net/personal-backup/thkuo/Saure/results.3/CH3657/cd/raxml_input/conc.prtn
col_constraint_tr: 
  /net/personal-backup/thkuo/Saure/results.3/CH3657/per-site_LogLikelihood/nuc_col_by_psll.nwk
best_ml_tree: 
  /net/personal-backup/thkuo/Saure/results.3/CH3657/cd/RAxML_bestTree.conc
bs_trees: 
  /net/personal-backup/thkuo/Saure/results.3/CH3657/cd/bootstrap/RAxML_bootstrap.all
bs_best_ml_tree: 
  /net/personal-backup/thkuo/Saure/results.3/CH3657/cd/RAxML_bipartitions.conc.bs
model:
  'GTRCAT -V'
max_cores: 8
